name: GitHub Secrets

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Test GH Secrets
      run: |
        echo "This is value $TEST_VALUE"
      env:
        TEST_VALUE: ${{ secrets.TEST }}
