name: Container service Example

on: ['workflow_dispatch']

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install dependancies
        run: npm cli
      - name: Connect to Postgres
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_POST: 5432
          
