# This is a workflow to call custom action

name: Custom GHA

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 8
          
      - name: Call Custom Action
        uses: ./.github/actions
        with:
          who-to-greet: test
          upload-path: "${{ github.workspace }}/Dockerfile, ${{ github.workspace }}/README.md"
      
