name: Input Parameters

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }}"

  failed:
    runs-on: ubuntu-latest

    steps:
      - name: greet
        run: |
          status="$('curl -Is http://www.google.co.in' | head -1)"
          validate=( $status )
          if [ "${validate[-2]}" == "200" ]; then
            echo "OK"
          else
            exit 1
          fi
          

  failed-run:
    needs: failed
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }}"
  
