name: Matrix Test

on:
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [green, pink]
        animal: [owl, magpie]
        include:
          - color: blue
            animal: owl
          - color: pink
            animal: magpie
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: echo 'colo - ${{ matrix.color }} & animal - ${{ matrix.animal }}'
