name: reusableWorkflowExample 

on:
  workflow_dispatch:
    inputs:
      input1:
        description: JobA
        required: true
        type: boolean
      input2:
        description: JobB
        required: true
        type: boolean
      input3:
        description: JobC
        required: true
        type: boolean
      InputName:
        description: name input
        required: true
        type: string     
jobs:
  CheckBranchandInputs:
    name: branch - ${{ github.ref_name }}
    runs-on: deere-ubuntu-latest
    
    steps:
      - name: Selected Inputs
        run: |
           echo "input1: ${{ github.event.inputs.input1 }}"
           echo "input2: ${{ github.event.inputs.input2 }}" 
           echo "input3: ${{ github.event.inputs.input3 }}" 
           echo "InputName: ${{ github.event.inputs.InputName }}"        
        
  CallingJobA:
    
    #if: github.event.inputs.input1 == 'true'
    #needs: CheckBranchandInputs
    uses: pbharambe/gitHub-action-demo/.github/workflows/jobA.yml@main
    with:
      InputName : ${{ github.event.inputs.InputName }}
      input1 : ${{ github.event.inputs.input1 }}
      
  CallingJobB:    
    
    #if: github.event.inputs.input2 == 'true'
    #needs: CallingJobA
    uses: pbharambe/gitHub-action-demo/.github/workflows/jobB.yml@main
    with:
      InputName : ${{ github.event.inputs.InputName }} 
      input2 : ${{ github.event.inputs.input2 }}              
