name: container

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main

jobs:
  node-docker:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.my_step.outputs.my_var }}
    container:
      image: 'node:14.15.0-alpine3.12'
    steps:
      - name: "Example output creation"
        id: "my_step"
        run: |
          my_var="Hello World"
          echo "Output [$my_var]"
          echo "my_var=$my_var" >> $GITHUB_OUTPUT
      - name: Log the parent container node version
        run: |
          node -v 
      - name: Step with docker to echo a string
        uses: 'docker://node:12.14.1-alpine3.10'
        with:
          entrypoint: /bin/echo
          args: Hello Docker !
