name: Input Parameters

on:
  workflow_dispatch:
  
parameters:
  UserOptionsA: 'optionA1,optionA2'
  UserOptionsB: 'optionB2,optionB3'

  AllOptionsA: ["optionA1", "optionA2", "optionA3"]
  AllOptionsB: ["optionB1", "optionB2", "optionB3"]

jobs:
  - job: job_with_options
    strategy:
      matrix:
        ${{ each optA in parameters.AllOptionsA }}:
          ${{ each optB in parameters.AllOptionsB }}:
            ${{ if and(contains(parameters.UserOptionsA, optA), contains(parameters.UserOptionsB, optB)) }}:
              ${{ format('{0}{1}', optA, optB) }}:
                optA_value: ${{ arch }}
                optB_value: ${{ flavor }}
